Redesign homepage
serify-health/website pull request #71
Opened 2017-06-19 20:32 UTC by HenryHins

2017-06-20 13:09 UTC, wparad commented
I'll be able to validate this when I get back to a computer ~1week.

2017-06-20 13:11 UTC, HenryHins commented
No worries

2017-06-28 19:58 UTC, wparad requested changes

2017-06-28 19:58 UTC, wparad commented on content/login/login.html
>      </div>
Almost everything looks good.  I like all the wording we have.  There is some image strangeness that I think we should clean up.  Take a look a screenshot, what can we do about that?

![2017-06-28-215820_1523x772_scrot](https://user-images.githubusercontent.com/5056218/27657433-f0d6c662-5c4c-11e7-9bf2-7b230d000bc9.png)

2017-06-29 00:36 UTC, HenryHins commented on content/login/login.html
>      </div>
Whoa are you using a 4K monitor or anything? What browser are you using?

2017-06-29 05:28 UTC, wparad commented
I saw a little bit of something strange and noticed it was different with size of the screen, so I zoomed all the way to see the extent of the issue.

2017-06-29 14:42 UTC, wparad approved these changes

2017-06-29 18:12 UTC, merged